### PR TITLE
Update architect-orb to 2.1.0

### PR DESCRIPTION
**Pull request by ubergesundheit**
Towards giantswarm/giantswarm#15898

### CODE REVIEW

**Comment by ubergesundheit** [comment]
Unsure who owns this component, hope batman is right.. 

Seems the github branch protection is not configured right..

**Review by rossf7 — COMMENTED** [review]
@ubergesundheit This is from the old style e2e tests that were replaced by the Tekton tests.

We should archive this and the other e2e* repos that are no longer needed. I'll do that today.

**Comment by ubergesundheit** [comment]
>  We should archive this and the other e2e* repos that are no longer needed. I'll do that today.

Nice thanks!

**Comment by rossf7** [comment]
@ubergesundheit Going to close this and will then archive.

**Pull request closed without merging**
